USE EMAIL_DB
GO

-- Step 1: Insert Languages
INSERT INTO LANGUAGES (NAME, CODE)
SELECT 'English', 'en' WHERE NOT EXISTS (SELECT * FROM LANGUAGES WHERE CODE = 'en');

INSERT INTO LANGUAGES (NAME, CODE)
SELECT 'Bulgarian', 'bg' WHERE NOT EXISTS (SELECT * FROM LANGUAGES WHERE CODE = 'bg');

-- Step 2: Fetch language IDs
DECLARE @EnglishId INT = (SELECT ID FROM LANGUAGES WHERE CODE = 'en');
DECLARE @BulgarianId INT = (SELECT ID FROM LANGUAGES WHERE CODE = 'bg');

-- Step 3: Insert Countries
INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE, LANGUAGE_CODE)
SELECT 'Unknown', '', @EnglishId WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Unknown');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE, LANGUAGE_CODE)
SELECT 'Bulgaria', '+359', @BulgarianId WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Bulgaria');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE, LANGUAGE_CODE)
SELECT 'United States', '+1', @EnglishId WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'United States');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE, LANGUAGE_CODE)
SELECT 'Canada', '+1', @EnglishId WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Canada');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE, LANGUAGE_CODE)
SELECT 'United Kingdom', '+44', @EnglishId WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'United Kingdom');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE, LANGUAGE_CODE)
SELECT 'Australia', '+61', @EnglishId WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Australia');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE, LANGUAGE_CODE)
SELECT 'Germany', '+49', @EnglishId WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Germany');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE, LANGUAGE_CODE)
SELECT 'France', '+33', @EnglishId WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'France');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE, LANGUAGE_CODE)
SELECT 'Spain', '+34', @EnglishId WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Spain');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE, LANGUAGE_CODE)
SELECT 'Italy', '+39', @EnglishId WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Italy');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE, LANGUAGE_CODE)
SELECT 'Brazil', '+55', @EnglishId WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Brazil');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE, LANGUAGE_CODE)
SELECT 'India', '+91', @EnglishId WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'India');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE, LANGUAGE_CODE)
SELECT 'China', '+86', @EnglishId WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'China');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE, LANGUAGE_CODE)
SELECT 'Japan', '+81', @EnglishId WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Japan');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE, LANGUAGE_CODE)
SELECT 'Russia', '+7', @EnglishId WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Russia');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE, LANGUAGE_CODE)
SELECT 'South Africa', '+27', @EnglishId WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'South Africa');

GO
