USE EMAIL_DB;
GO

INSERT INTO LANGUAGES (NAME, CODE)
SELECT 'English', 'en' WHERE NOT EXISTS (SELECT * FROM LANGUAGES WHERE CODE = 'en');

INSERT INTO LANGUAGES (NAME, CODE)
SELECT 'Bulgarian', 'bg' WHERE NOT EXISTS (SELECT * FROM LANGUAGES WHERE CODE = 'bg');

DECLARE @EnglishId INT = (SELECT ID FROM LANGUAGES WHERE CODE = 'en');
DECLARE @BulgarianId INT = (SELECT ID FROM LANGUAGES WHERE CODE = 'bg');
DECLARE @Context INT = 1;

TRUNCATE TABLE LANG_SUPPORT
INSERT INTO LANG_SUPPORT (MESSAGE_NAME, VALUE, CONTEXT, LANGUAGE_ID)
VALUES
('Statistics', 'Statistics', @Context, @EnglishId),
('MyAccount', 'My Account', @Context, @EnglishId),
('UserAccount', 'User Account', @Context, @EnglishId),
('Container', 'Container', @Context, @EnglishId),
('ExitConfirmation', 'Are you sure you want to exit the application?', @Context, @EnglishId),
('ConfirmExit', 'Confirm Exit', @Context, @EnglishId),
('WriteNew', 'Write New', @Context, @EnglishId),
('Filter', 'Filter', @Context, @EnglishId),
('Date', 'Date', @Context, @EnglishId),
('Subject', 'Subject', @Context, @EnglishId),
('Content', 'Content', @Context, @EnglishId),
('SortByDate', 'Sort by date', @Context, @EnglishId),
('FromTo', 'From/To', @Context, @EnglishId),
('ClearFilter', 'Clear Filter', @Context, @EnglishId),
('MakeAnnouncement', 'Make Announcement', @Context, @EnglishId),
('SenderEmail', 'Sender Email', @Context, @EnglishId),
('ReceiverEmail', 'Receiver Email', @Context, @EnglishId),
('MoveToBin', 'Move to bin', @Context, @EnglishId),
('Refresh', 'Refresh', @Context, @EnglishId),
('RemoveFromFolder', 'Remove from folder', @Context, @EnglishId),
('ActionAvailableOnCustomFolders', 'This action is only available in custom folders.', @Context, @EnglishId),
('InvalidOperation', 'Invalid Operation', @Context, @EnglishId),
('FailedToRemoveEmail', 'Failed to remove email(s) from folder.', @Context, @EnglishId),
('Error', 'Error', @Context, @EnglishId),
('MoveToFolder', 'Move To Folder', @Context, @EnglishId),
('FailedToMoveToFolder', 'Failed to move email(s).', @Context, @EnglishId),
('MarkAsRead', 'Mark as read', @Context, @EnglishId),
('MarkAsUnread', 'Mark as unread', @Context, @EnglishId),
('DraftEmail', 'Draft email', @Context, @EnglishId),
('SentEmail', 'Sent email', @Context, @EnglishId),
('Sender', 'Sender', @Context, @EnglishId),
('ReceivedEmail', 'Received Email', @Context, @EnglishId),
('Send', 'Send', @Context, @EnglishId),
('Close', 'Close', @Context, @EnglishId),
('NewEmail', 'New Email', @Context, @EnglishId),
('Uplaod', 'Uplaod', @Context, @EnglishId),
('Download', 'Downlaod', @Context, @EnglishId),
('Remove', 'Remove', @Context, @EnglishId),
('Email', 'Email', @Context, @EnglishId),
('ByDate', 'By Date', @Context, @EnglishId),
('EndDate', 'End Date', @Context, @EnglishId),
('BeginDate', 'Begin Date', @Context, @EnglishId),
('ByEmail', 'By Email', @Context, @EnglishId),
('Apply', 'Apply', @Context, @EnglishId),
('Clear', 'Clear', @Context, @EnglishId),
('FilterEmails', 'Filter Emails', @Context, @EnglishId),
('ExtendedFilters', 'Extended Filters', @Context, @EnglishId),
('FileDownloadSuccessfully', 'File downloaded successfully.', @Context, @EnglishId),
('DownloadFile', 'Download File', @Context, @EnglishId),
('Folders', 'Folders', @Context, @EnglishId),
('Deleted', 'Deleted', @Context, @EnglishId),
('Incoming', 'Incoming', @Context, @EnglishId),
('Outgoing', 'Outgoing', @Context, @EnglishId),
('NewFolderEditing', 'New Folder (editing...)', @Context, @EnglishId),
('FailedToAddFolder', 'Failed to add folder', @Context, @EnglishId),
('Add', 'Add', @Context, @EnglishId),
('Delete', 'Delete', @Context, @EnglishId),
('ChangePassword', 'Change Password', @Context, @EnglishId),
('OldPassWord', 'Old Password', @Context, @EnglishId),
('NewPassword', 'New Password', @Context, @EnglishId),
('RepeatPassword', 'Repeat password', @Context, @EnglishId),
('OK', 'OK', @Context, @EnglishId),
('LogIn', 'Log In', @Context, @EnglishId),
('EmailUsername', 'Email/Username', @Context, @EnglishId),
('Password', 'Password', @Context, @EnglishId),
('DontHaveAccount', 'Dont have an account? Register!', @Context, @EnglishId),
('Register', 'Register', @Context, @EnglishId),
('Name', 'Name', @Context, @EnglishId),
('SeyUpProfile', 'Set up profile', @Context, @EnglishId),
('ProfilePicture', 'Profile Picture', @Context, @EnglishId),
('Continue', 'Continue', @Context, @EnglishId),
('Welcome', 'Welcome', @Context, @EnglishId),
('NumberOfUsers', 'Number of users', @Context, @EnglishId),
('NumberOfOutgoingEmail', 'Number of outgoing emails', @Context, @EnglishId),
('NumberOfIncomingEmails', 'Numbers of incoming emails', @Context, @EnglishId),
('Save', 'Save', @Context, @EnglishId),
('Edit', 'Edit', @Context, @EnglishId),
('FailedToSaveChanges', 'Failed to save changes.', @Context, @EnglishId),
('ProfileUpdatedSuccessfully', 'Profile updated successfully.', @Context, @EnglishId),
('Saved', 'Saved', @Context, @EnglishId),
('LogOut', 'Log out', @Context, @EnglishId),
('EmailPost', 'Email:', @Context, @EnglishId),
('NamePost', 'Name:', @Context, @EnglishId),
('CountryPost', 'Country:', @Context, @EnglishId),
('PhoneNumberPost', 'Phone Number:', @Context, @EnglishId),
('ChangeLanguageQuestion', 'The selected country has a default language. Do you want to switch your interface language accordingly?', @Context, @EnglishId),
('ChangeLanguage', 'Change Language', @Context, @EnglishId),
('Drafts', N'Drafts', @Context, @EnglishId),
('RestartNeeded', N'Restarting of the applciation is need for the changes to take effect', @Context, @EnglishId),
('Receiver', N'Receiver', @Context, @EnglishId),
('Files', N'Files', @Context, @EnglishId),
('OrderByAscending', N'Ascending', @Context, @EnglishId),
('OrderByDescending', N'Descending', @Context, @EnglishId)

-- Bulgarian translations
-- Bulgarian translations (Unicode-safe)
INSERT INTO LANG_SUPPORT (MESSAGE_NAME, VALUE, CONTEXT, LANGUAGE_ID)
VALUES
('Statistics', N'Статистика', @Context, @BulgarianId),
('MyAccount', N'Моят профил', @Context, @BulgarianId),
('UserAccount', N'Потребителски профил', @Context, @BulgarianId),
('Container', N'Контейнер', @Context, @BulgarianId),
('ExitConfirmation', N'Сигурни ли сте, че искате да излезете от приложението?', @Context, @BulgarianId),
('ConfirmExit', N'Потвърди изход', @Context, @BulgarianId),
('WriteNew', N'Напиши ново', @Context, @BulgarianId),
('Filter', N'Филтър', @Context, @BulgarianId),
('Date', N'Дата', @Context, @BulgarianId),
('Subject', N'Тема', @Context, @BulgarianId),
('Content', N'Съдържание', @Context, @BulgarianId),
('SortByDate', N'Сортирай по дата', @Context, @BulgarianId),
('FromTo', N'От/До', @Context, @BulgarianId),
('ClearFilter', N'Изчисти филтъра', @Context, @BulgarianId),
('MakeAnnouncement', N'Направи съобщение', @Context, @BulgarianId),
('SenderEmail', N'Имейл на подател', @Context, @BulgarianId),
('ReceiverEmail', N'Имейл на получател', @Context, @BulgarianId),
('MoveToBin', N'Премести в кошчето', @Context, @BulgarianId),
('Refresh', N'Обнови', @Context, @BulgarianId),
('RemoveFromFolder', N'Премахни от папка', @Context, @BulgarianId),
('ActionAvailableOnCustomFolders', N'Тази операция е възможна само в персонализирани папки.', @Context, @BulgarianId),
('InvalidOperation', N'Невалидна операция', @Context, @BulgarianId),
('FailedToRemoveEmail', N'Неуспешно премахване на имейл(и).', @Context, @BulgarianId),
('Error', N'Грешка', @Context, @BulgarianId),
('MoveToFolder', N'Премести в папка', @Context, @BulgarianId),
('FailedToMoveToFolder', N'Неуспешно преместване.', @Context, @BulgarianId),
('MarkAsRead', N'Маркирай като прочетено', @Context, @BulgarianId),
('MarkAsUnread', N'Маркирай като непрочетено', @Context, @BulgarianId),
('DraftEmail', N'Чернова', @Context, @BulgarianId),
('SentEmail', N'Изпратен имейл', @Context, @BulgarianId),
('Sender', N'Подател', @Context, @BulgarianId),
('ReceivedEmail', N'Получен имейл', @Context, @BulgarianId),
('Send', N'Изпрати', @Context, @BulgarianId),
('Close', N'Затвори', @Context, @BulgarianId),
('NewEmail', N'Нов имейл', @Context, @BulgarianId),
('Uplaod', N'Качи', @Context, @BulgarianId),
('Download', N'Изтегли', @Context, @BulgarianId),
('Remove', N'Премахни', @Context, @BulgarianId),
('Email', N'Имейл', @Context, @BulgarianId),
('ByDate', N'По дата', @Context, @BulgarianId),
('EndDate', N'Крайна дата', @Context, @BulgarianId),
('BeginDate', N'Начална дата', @Context, @BulgarianId),
('ByEmail', N'По имейл', @Context, @BulgarianId),
('Apply', N'Приложи', @Context, @BulgarianId),
('Clear', N'Изчисти', @Context, @BulgarianId),
('FilterEmails', N'Филтрирай имейли', @Context, @BulgarianId),
('ExtendedFilters', N'Разширени филтри', @Context, @BulgarianId),
('FileDownloadSuccessfully', N'Файлът е изтеглен успешно.', @Context, @BulgarianId),
('DownloadFile', N'Изтегли файл', @Context, @BulgarianId),
('Folders', N'Папки', @Context, @BulgarianId),
('Deleted', N'Изтрити', @Context, @BulgarianId),
('Incoming', N'Входящи', @Context, @BulgarianId),
('Outgoing', N'Изходящи', @Context, @BulgarianId),
('NewFolderEditing', N'Нова папка (редакция...)', @Context, @BulgarianId),
('FailedToAddFolder', N'Неуспешно добавяне на папка', @Context, @BulgarianId),
('Add', N'Добави', @Context, @BulgarianId),
('Delete', N'Изтрий', @Context, @BulgarianId),
('ChangePassword', N'Промени парола', @Context, @BulgarianId),
('OldPassWord', N'Стара парола', @Context, @BulgarianId),
('NewPassword', N'Нова парола', @Context, @BulgarianId),
('RepeatPassword', N'Повтори паролата', @Context, @BulgarianId),
('OK', N'ОК', @Context, @BulgarianId),
('LogIn', N'Вход', @Context, @BulgarianId),
('EmailUsername', N'Имейл/Потребителско име', @Context, @BulgarianId),
('Password', N'Парола', @Context, @BulgarianId),
('DontHaveAccount', N'Нямате акаунт? Регистрирайте се!', @Context, @BulgarianId),
('Register', N'Регистрация', @Context, @BulgarianId),
('Name', N'Име', @Context, @BulgarianId),
('SeyUpProfile', N'Настройване на профил', @Context, @BulgarianId),
('ProfilePicture', N'Профилна снимка', @Context, @BulgarianId),
('Continue', N'Продължи', @Context, @BulgarianId),
('Welcome', N'Добре дошли', @Context, @BulgarianId),
('NumberOfUsers', N'Брой потребители', @Context, @BulgarianId),
('NumberOfOutgoingEmail', N'Брой изходящи имейли', @Context, @BulgarianId),
('NumberOfIncomingEmails', N'Брой входящи имейли', @Context, @BulgarianId),
('Save', N'Запази', @Context, @BulgarianId),
('Edit', N'Редакция', @Context, @BulgarianId),
('FailedToSaveChanges', N'Неуспешно запазване на промените.', @Context, @BulgarianId),
('ProfileUpdatedSuccessfully', N'Профилът е обновен успешно.', @Context, @BulgarianId),
('Saved', N'Запазено', @Context, @BulgarianId),
('LogOut', N'Изход', @Context, @BulgarianId),
('EmailPost', N'Имейл:', @Context, @BulgarianId),
('NamePost', N'Име:', @Context, @BulgarianId),
('CountryPost', N'Държава:', @Context, @BulgarianId),
('PhoneNumberPost', N'Телефонен номер:', @Context, @BulgarianId),
('ChangeLanguageQuestion', N'Избраната държава има основен език. Желаете ли да го използвате като интерфейсен език?', @Context, @BulgarianId),
('ChangeLanguage', N'Смяна на езика', @Context, @BulgarianId),
('Drafts', N'Чернови', @Context, @BulgarianId),
('RestartNeeded', N'Нужно е рестартиране на приложението за да се приложат новите настройки', @Context, @BulgarianId),
('Receiver', N'Получател', @Context, @BulgarianId),
('Files', N'Файлове', @Context, @BulgarianId),
('OrderByAscending', N'Възходящо', @Context, @BulgarianId),
('OrderByDescending', N'Низходящо', @Context, @BulgarianId)
