USE EMAIL_DB
GO

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE)
SELECT 'United States', '+1' WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'United States');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE)
SELECT 'Canada', '+1' WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Canada');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE)
SELECT 'United Kingdom', '+44' WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'United Kingdom');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE)
SELECT 'Australia', '+61' WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Australia');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE)
SELECT 'Germany', '+49' WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Germany');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE)
SELECT 'France', '+33' WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'France');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE)
SELECT 'Spain', '+34' WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Spain');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE)
SELECT 'Italy', '+39' WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Italy');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE)
SELECT 'Brazil', '+55' WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Brazil');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE)
SELECT 'India', '+91' WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'India');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE)
SELECT 'China', '+86' WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'China');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE)
SELECT 'Japan', '+81' WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Japan');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE)
SELECT 'Russia', '+7' WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'Russia');

INSERT INTO COUNTRIES (NAME, PHONE_NUMBER_CODE)
SELECT 'South Africa', '+27' WHERE NOT EXISTS (SELECT * FROM COUNTRIES WHERE NAME = 'South Africa');

GO
